apiVersion: v1
kind: Service
metadata:
  name: green-agent
  labels:
    app: green-agent
spec:
  type: ClusterIP
  ports:
  - name: dashboard
    port: 8000
    targetPort: 8000
  - name: ray-dashboard
    port: 8265
    targetPort: 8265
  selector:
    app: green-agent
