apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: green-agent-cluster
spec:
  headGroupSpec:
    template:
      spec:
        containers:
        - name: ray-head
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
  workerGroupSpecs:
  - replicas: 2
    minReplicas: 1
    maxReplicas: 4
    groupName: standard-workers
    rayStartParams:
      num-cpus: '2'
      memory: '4294967296'
    template:
      spec:
        containers:
        - name: ray-worker
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
